# Generated by Django 4.2.4 on 2023-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('distribuidorId', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDistribuidor', models.CharField(blank=True, max_length=30, verbose_name='nombreDistribuidor')),
                ('categoria', models.CharField(max_length=15, verbose_name='categoria')),
                ('comision', models.FloatField(verbose_name='comision')),
            ],
        ),
    ]
