# Generated by Django 4.2.4 on 2023-11-10 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Distribuidor', '0004_distribuidor_extensiondominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribuidor',
            name='extensionDominio',
        ),
        migrations.CreateModel(
            name='ExtensionDominio',
            fields=[
                ('extensionId', models.AutoField(primary_key=True, serialize=False)),
                ('extensionDominio', models.CharField(max_length=4, null='True', verbose_name='extensionDominio')),
                ('distribuidorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribuidor.distribuidor')),
            ],
        ),
    ]
