# Generated by Django 4.2.4 on 2023-11-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribuidor', '0005_remove_distribuidor_extensiondominio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensiondominio',
            options={'ordering': ('extensionDominio',)},
        ),
        migrations.AlterField(
            model_name='extensiondominio',
            name='extensionDominio',
            field=models.CharField(max_length=10, null='True', verbose_name='extensionDominio'),
        ),
    ]
