# Generated by Django 4.2.4 on 2023-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribuidor', '0006_alter_extensiondominio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensiondominio',
            name='precioExtension',
            field=models.FloatField(null=True, verbose_name='precioExtension'),
        ),
    ]
