# Generated by Django 4.2.4 on 2023-10-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=20, verbose_name='nombre')),
                ('fechaNacimientoCliente', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('emailCliente', models.CharField(max_length=30, verbose_name='emailCliente')),
                ('paisCliente', models.CharField(max_length=10, verbose_name='paisCliente')),
                ('ciudadCliente', models.CharField(max_length=15, verbose_name='ciudadCliente')),
                ('contraseniaCliente', models.CharField(blank=True, max_length=20, null=True)),
                ('planCliente', models.CharField(blank=True, max_length=20, null=True, verbose_name='plan')),
                ('ClienteActivo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='paqueteHosting',
            fields=[
                ('paqueteId', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePaquete', models.CharField(blank=True, max_length=15, verbose_name='Paquete')),
                ('plataforma', models.CharField(blank=True, max_length=15, verbose_name='plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=False)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('tarjetaId', models.AutoField(primary_key=True, serialize=False)),
                ('numeroTarjeta', models.BigIntegerField(max_length=18, verbose_name='tarjeta numero')),
                ('cvc', models.IntegerField(max_length=3)),
                ('fechaVencimiento', models.CharField(max_length=10, verbose_name='Fecha de vencimiento')),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SitioWeb',
            fields=[
                ('webid', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDominio', models.CharField(blank=True, max_length=30, verbose_name='dominio')),
                ('fechaSolicitus', models.CharField(blank=True, max_length=10, verbose_name='Fecha desolicitus')),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
    ]
