# Generated by Django 4.2.4 on 2023-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nombreCliente',)},
        ),
        migrations.AlterModelOptions(
            name='paquetehosting',
            options={'ordering': ('nombrePaquete',)},
        ),
        migrations.AlterModelOptions(
            name='sitioweb',
            options={'ordering': ('nombreDominio',)},
        ),
        migrations.AlterModelOptions(
            name='tarjetacredito',
            options={'ordering': ('clienteId',)},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('ticketid',)},
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarioCliente',
            field=models.CharField(max_length=20, null=True, verbose_name='nombre'),
        ),
    ]
