# Generated by Django 4.2.4 on 2023-10-29 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cliente', '0003_cliente_last_login_alter_cliente_usuariocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('caracteristicaId', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristica', models.TextField(verbose_name='caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planId', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePlan', models.CharField(blank=True, max_length=15, verbose_name='paquete')),
                ('descripcionPlan', models.TextField(verbose_name='descripcion')),
                ('precioMensual', models.IntegerField(verbose_name='precio')),
                ('caracteristicasPlan', models.ManyToManyField(to='Cliente.caracteristica')),
            ],
            options={
                'ordering': ('nombrePlan',),
            },
        ),
        migrations.DeleteModel(
            name='paqueteHosting',
        ),
        migrations.AlterModelOptions(
            name='sitioweb',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tarjetacredito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='id',
            new_name='clienteId',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contraseniaCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='planCliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuarioCliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='planId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.plan'),
        ),
    ]
