# Generated by Django 4.2.4 on 2023-10-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_caracteristica_plan_delete_paquetehosting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitioweb',
            name='fechaSolicitus',
        ),
        migrations.AddField(
            model_name='sitioweb',
            name='fechaSolicitud',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Fecha desolicitud'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='emailCliente',
            field=models.EmailField(max_length=30, verbose_name='emailCliente'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='cvc',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fechaVencimiento',
            field=models.DateField(max_length=10, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='numeroTarjeta',
            field=models.CharField(max_length=18, verbose_name='tarjeta numero'),
        ),
    ]
