# Generated by Django 4.2.4 on 2023-10-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0005_remove_sitioweb_fechasolicitus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tituloPlan',
            field=models.TextField(null=True, verbose_name='titulo'),
        ),
    ]
