# Generated by Django 4.2.4 on 2023-10-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0006_plan_tituloplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nombrePlan',
            field=models.CharField(blank=True, max_length=20, verbose_name='paquete'),
        ),
    ]
