# Generated by Django 4.2.4 on 2023-10-29 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0007_alter_plan_nombreplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='cvc',
            field=models.CharField(default='NE', max_length=3),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fechaVencimiento',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='numeroTarjeta',
            field=models.CharField(default='NE', max_length=18, verbose_name='tarjeta numero'),
        ),
    ]
