# Generated by Django 4.2.4 on 2023-11-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0008_alter_tarjetacredito_cvc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='direccion',
            field=models.CharField(max_length=50, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='cvc',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='numeroTarjeta',
            field=models.CharField(max_length=18, verbose_name='tarjeta numero'),
        ),
    ]
