# Generated by Django 4.2.4 on 2023-11-10 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Distribuidor', '0005_remove_distribuidor_extensiondominio_and_more'),
        ('Cliente', '0009_tarjetacredito_direccion_alter_tarjetacredito_cvc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitioweb',
            old_name='webid',
            new_name='webId',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketid',
            new_name='ticketiId',
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('dominioId', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='Sin usar', max_length=15, verbose_name='estadoDominio')),
                ('nombreDominio', models.CharField(max_length=100, verbose_name='nombreDominio')),
                ('clienteId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('extensionDominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribuidor.extensiondominio')),
            ],
        ),
    ]
