# Generated by Django 4.2.4 on 2023-11-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0010_rename_webid_sitioweb_webid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dominio',
            options={'ordering': ('nombreDominio',)},
        ),
    ]
