# Generated by Django 4.2.4 on 2023-11-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0011_alter_dominio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='fechaSolicitud',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='fechaSolicitud'),
        ),
        migrations.AddField(
            model_name='dominio',
            name='tiempoPropiedad',
            field=models.IntegerField(null=True, verbose_name='tiempoPropiedad'),
        ),
        migrations.AddField(
            model_name='sitioweb',
            name='tiempoHosteo',
            field=models.IntegerField(null=True, verbose_name='tiempoHosteo'),
        ),
    ]
