# Generated by Django 4.2.4 on 2023-11-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0013_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='fechaCancelacion',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='fechaCancelación'),
        ),
    ]
