# Generated by Django 4.2.6 on 2023-11-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0015_remove_tarjetacredito_fechavencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='fechaVencimientoAño',
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='fechaVencimientoAnio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha anio'),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fechaVencimientoMes',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha mes'),
        ),
    ]
