# Generated by Django 4.2.4 on 2023-11-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Distribuidor', '0007_extensiondominio_precioextension'),
        ('Cliente', '0018_remove_sitioweb_nombredominio_sitioweb_dominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominio',
            name='fechaCancelacion',
        ),
        migrations.CreateModel(
            name='DominioCancelado',
            fields=[
                ('dominioId', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDominio', models.CharField(max_length=100, verbose_name='nombreDominio')),
                ('fechaSolicitud', models.DateField(blank=True, max_length=10, null=True, verbose_name='fechaSolicitud')),
                ('fechaCancelacion', models.DateField(blank=True, max_length=10, null=True, verbose_name='fechaCancelación')),
                ('clienteId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('extensionDominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribuidor.extensiondominio')),
            ],
            options={
                'ordering': ('nombreDominio',),
            },
        ),
    ]
