# Generated by Django 4.2.4 on 2023-11-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0019_remove_dominio_fechacancelacion_dominiocancelado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitioweb',
            name='tiempoHosteo',
        ),
    ]
