# Generated by Django 4.2.4 on 2023-11-26 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0020_remove_sitioweb_tiempohosteo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketiId',
            new_name='ticketId',
        ),
    ]
