# Generated by Django 4.2.4 on 2023-11-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0021_rename_ticketiid_ticket_ticketid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
