# Generated by Django 4.2.6 on 2023-11-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0022_ticket_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
