# Generated by Django 4.2.4 on 2023-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmpleado', models.CharField(max_length=20, verbose_name='nombre')),
                ('fechaNacimientoEmpleado', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('cargoEmpleado', models.CharField(max_length=15, verbose_name='cargoEmpleado')),
                ('inicioContrato', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefonoEmpleado', models.CharField(max_length=20)),
                ('emailEmpleado', models.CharField(max_length=30, verbose_name='emailEmpleado')),
                ('contraseniaEmpleado', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
