# Generated by Django 4.2.4 on 2023-10-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0003_empleado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='contraseniaEmpleado',
        ),
    ]
